### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by bwaltz** [ColbyCommunications/colby-college-theme#10]
Get the search interface working.

The Algolia index we'll be using is named `prod_colbyedu_aggregated`.

The vue code for our news site is here:

https://github.com/ColbyCommunications/colby-news-theme/tree/master/vue

and more specifically:
https://github.com/ColbyCommunications/colby-news-theme/blob/master/vue/components/Algolia.vue

**Comment by gregoryspragginsjr** [comment]
Hey @bwaltz just a wanted to follow up here; its looking like I've got algolia successfully integrated into the codebase using the index you provided (you can see in my provided screen capture that I'm using `Athletics` as a test search term).
<img width="1440" alt="Screen Shot 2022-10-31 at 2 39 17 PM" src="https://user-images.githubusercontent.com/10871717/199085983-2febd2c6-f3f8-4dee-95e9-2d7d675b483c.png">

I just wanted to circle back one last time before styling the UI and make sure you all are okay with me deploying the `table` component as the proper visuals for displaying search results (as it was originally designed), or did you want to go with something a little more visual (maybe an `article-grid` like whats currently on post category pages)? I only ask because we've made a few tweeks to visuals during dev already in a few of the other index/archive pages, and wanted to give you an opportunity to amend if necessary. Otherwise, we're close to completion here.
<img width="1440" alt="Screen Shot 2022-10-31 at 2 48 14 PM" src="https://user-images.githubusercontent.com/10871717/199086177-6ac8f076-48aa-4558-ae40-8353882a3215.png">

**Comment by bwaltz** [comment]
@gregoryspragginsjr great question. I will confer with my team. We may actually want to use the article grid here. Since we have results coming from all the subdomains, each result has a originIndexLabel, which houses the name of the site that we want to display with each result.

![Screen Shot 2022-11-01 at 10 49 52 AM](https://user-images.githubusercontent.com/2333967/199262595-6bcc694c-9eb7-44e0-9cd5-f7a9ca4eaa76.png)

Not sure if the article grid is the most effective display or if there's another design option that may be better.

**Comment by gregoryspragginsjr** [comment]
@bwaltz I think the `article-grid` will suffice here. I'll dig into the query results from algolia and should be able to discern proper aesthetics from there. Should have something for you by the end of the day.

**Comment by gregoryspragginsjr** [comment]
@bwaltz this is ready for review via my latest commit at: https://github.com/ColbyCommunications/colby-college-theme/commit/2d9a438a19eafed2e23b2a0754d51f62a77f121e

I suggest adding a page aptly named `Search`. Our custom `page-search.twig` template should take things from there.

**Comment by bwaltz** [comment]
@gregoryspragginsjr is this supposed to work with the search button in the top utility nav? It doesn't look like it does.

https://master-7rqtwti-ouiqvb5juucvu.us-4.platformsh.site/

It works when you go to the search page:

https://master-7rqtwti-ouiqvb5juucvu.us-4.platformsh.site/search/

Instead of just sending people to the search page from the button, we'd really like to have a modal search experience, similar to our News site and similar to like https://www.swarthmore.edu/. I like how Swarthmore makes searching its own experience.

We'd definitely like to have highlighting, similar to our news site search.

**Comment by gregoryspragginsjr** [comment]
@bwaltz Hey Brandon; it does not. As per the designs, the search button in the top utility nav was meant to simply link off to a separate search page. We do not have a mock-up handy for this, nor do we have an internal modal component ready to deploy. We could, of course, whip this experience up for you (technically, the entire search component could be dumped into a modal) but I'd have to circle back with my internal team for a more formal design and timing.

**Comment by bwaltz** [comment]
@gregoryspragginsjr we do want to pursue the modal solution. Even if we just dump the existing experience into a modal. We understand the considerations of using modals on mobile.

Let me know next steps if we need to have a more formal process with the wider team.

**Comment by gregoryspragginsjr** [comment]
@bwaltz this experience has now been ported to a modal, similar to whats going on in current courses as of my recent commit at: https://github.com/ColbyCommunications/colby-college-theme/commit/55205f5d846a649370f688374bda2cb8966d0751

Please confirm, and close when ready.

**Comment by gregoryspragginsjr** [comment]
Hey @bwaltz 
My latest commit here should cover everything remaining for search functionality. To quickly recap:

1. The component will reset whenever closed, clearing the search query
2. Query highlighting has been added
3. Query results will clear whenever search input is empty as discussed

Also wanted to note, we do have the option of changing the color of the highlight here if this is something that interests you. I attempted to utilize our canary yellow from the styleguide, but it wasnt as nice as I expected, so I've settled with the default yellow like whats being used in colby news. Please confirm and close when you're ready.

**Comment by bwaltz** [comment]
@gregoryspragginsjr I made some changes to the search. You can check them out here: https://github.com/ColbyCommunications/colby-college-theme/commit/bf68b7d0b63a4974f3aef01cfa5a20c1c655d76f

I think at this point we are good with search. I will close.
