### ISSUE TITLE
Style events embed on department pages

### ISSUE THREAD

**Issue by bwaltz** [ColbyCommunications/colby-college-theme#12]
For example, see this page:

https://master-7rqtwti-ouiqvb5juucvu.us-4.platformsh.site/academics/departments-and-programs/art/

![Screen Shot 2022-10-25 at 1 50 19 PM](https://user-images.githubusercontent.com/2333967/197846091-c81f3443-47fd-455e-bdcb-88c51b908d91.png)

The embedded markup needs to be styled like the designs in Figma. We are hoping this can go into the theme code instead of Livewhale.

**Comment by bwaltz** [comment]
Here's the embed for spanish:

`<div class="lwcw" data-options="id=5&format=html&group=Spanish"></div> <script type="text/javascript" id="lw_lwcw" src="//events.colby.edu/livewhale/theme/core/scripts/lwcw.js"></script>`

**Comment by gregoryspragginsjr** [comment]
@bwaltz I've pushed a commit to address these stylistic changes at: https://github.com/ColbyCommunications/colby-college-theme/commit/d8a624a322a70cbd99d591b00087aa3b96145304

Please note, locally I cannot get the events to render due to what appears to be a CORS issue, so I wont be able to verify this is good until the next deployment. Let me know when you run your next composer deployment, and take a look.

Also note, because I couldnt see the rendering locally, I dumped the Spanish embed onto the art page temporarily to see the markup. We can remove once this has been confirmed complete.
