### ISSUE TITLE
Course catalogue table filtering 

### ISSUE THREAD

**Issue by bwaltz** [ColbyCommunications/colby-college-theme#31]
A few questions here. It looks like in the designs there was a way to filter and search the table, is this still a possibility?

![Screen Shot 2022-11-01 at 1 31 20 PM](https://user-images.githubusercontent.com/2333967/199299209-c5072702-f83a-4445-a628-76b43c6f8180.png)

We'd also like to see if it's possible to add some additional filtering options on that course catalogue table. Is it possible to, in addition to the department selector dropdown, have the same filters for "fall," "spring," and "January?" In this case, the filters would be independent of each other so you'd be able to select a department and also select "fall" or select "fall" and then select a department.

Possible?

**Comment by gregoryspragginsjr** [comment]
Hey @bwaltz,
A few things here:

- Input search is very possible, and I have added this feature in a recent commit at: https://github.com/ColbyCommunications/colby-college-theme/commit/3bf8b33bbc63e2c3a0d7b8f85ffd2ff03200c457
The reason why this was previously withheld was because, as you recall, we were pulling from separate API endpoints for courses, and those endpoints were begetting some inconsistent property names making things challenging to find a consistent solution that worked across the board. Since your call to consolidate endpoints, (at least in regards to courses) we can now move forward with searching through item titles. Give it a test run, and let me know your thoughts.
- I've added semester filters to the main `Course Catalog` table, so you should see Fall, Spring, and January pop up there.
- In regards to the dropdown request, this should also be possible and Ill be taking a look in a bit but I would lightly caution; it technically creates redundancy between the course catalog page, and what essentially is being done on individual department pages (display courses per department) albiet in a manner that is more akin to a live reload situation. If you think this will still be valuable, we can get it done.

**Comment by bwaltz** [comment]
@gregoryspragginsjr yes we think this is still valuable.

**Comment by gregoryspragginsjr** [comment]
@bwaltz this feature has finally been integrated as of my latest commit at: https://github.com/ColbyCommunications/colby-college-theme/commit/4f1122e056aa69fda62012121666a1f9f220d2e6

Please verify and let me know if things are behaving as expected, and close this ticket when done.

**Comment by bwaltz** [comment]
@gregoryspragginsjr 

It works pretty well! I do say! However, I did find an oddity. For example, this situation is weird to me:

![Screen Shot 2022-11-10 at 9 26 52 AM](https://user-images.githubusercontent.com/2333967/201118973-23d88a88-664f-49f3-b337-b22bfba05f59.png)

I'm searching on the work "practice" and it seems not many of the titles have that word in them. And it's only returning Art rows.

**Comment by gregoryspragginsjr** [comment]
@bwaltz I've committed another change that should adjust the search query a little bit, but I think this maybe an edge case. The module is thinking words like `painting` are too close to `practice` within the art category, which is why you're seeing the results here. We could go on and tweak this indefinitely as we move along, but if your good  with the core functionality here, then we should be good to close this ticket.
